apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels: # label of pod
    run: ashupod22
  name: ashupod23 # name of pod 
spec:
  volumes: # to create volume of diff type
  - name: ashuvol1
    hostPath: # will take space from minion node 
     path: /ashudata1 # this location will be created in minion node
     type: DirectoryOrCreate # if above location not present then it will be created
  containers:
  - image: nginx 
    name: ashuc4 
    volumeMounts:
    - name: ashuvol1
      mountPath: /usr/share/nginx/html/
      readOnly: True 
  - image: alpine
    name: ashupod22
    volumeMounts: # to attach volume in container 
    - name: ashuvol1 # name of volume 
      mountPath: /mnt/vol1 # location inside container 
    command: ["sh","-c","while true;do date >>/mnt/vol1/time.txt;sleep 10;done"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
