apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashusvc1
  name: ashusvc1 # name of service 
  namespace: ashu-space # namespace info 
spec:
  ports:
  - name: 1234-3000
    port: 1234 # port of service 
    protocol: TCP
    targetPort: 3000 # port of app 
  selector: # Pod finder using given label 
    ashu: nodeapp1 # label of pod 
  type: NodePort # type of service 
status:
  loadBalancer: {}
